### PR TITLE
update for new SDP format

### LINKED ISSUE #140: update for new SDP format
Opening an issue to keep track of updating Convex.jl for the new SDP format in MathProgBase 0.5 (https://github.com/JuliaOpt/MathProgBase.jl/pull/108). At this point all of the solvers have been updated.
@chriscoey and I need this to test MISDP with Pajarito.

### PR DESCRIPTION
**Pull request by mlubin**
Let's see if this passes travis. CC @chriscoey
Closes #140

### CODE REVIEW

**Comment by mlubin** [comment]
Green on 0.4

**Comment by mlubin** [comment]
@madeleineudell, any objections to merging and tagging?

**Comment by madeleineudell** [comment]
Looks good!

**Comment by madeleineudell** [comment]
Miles, go ahead and tag master with v0.3.0 now. I'd do it myself but the
versioning on my system seems to be messed up.

On Wed, Jun 15, 2016 at 3:55 PM, Miles Lubin <notifications@github.com>
wrote:

> @madeleineudell <https://github.com/madeleineudell>, any objections to
> merging and tagging?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/pull/143#issuecomment-226343979>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyp9N26adZBz3Lgh2kn0ehcBvP3g4Uaks5qMIL9gaJpZM4Izw-E>
> .
>



-- 
Madeleine Udell
Assistant Professor, Operations Research and Information Engineering
Cornell University
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Pull request merged**
