### PR TITLE
Allow setting max print width of IDs via `Convex.MAXDIGITS`.

### PR DESCRIPTION
**Pull request by riccardomurri**
Follow-up to https://discourse.julialang.org/t/convex-jl-how-to-print-full-variable-id/35917

### CODE REVIEW

**Comment by ericphanson** [comment]
Thanks, looks great! Any ideas on how to test it? Maybe just check the length of the result of `show_id` before changing the setting is small and see that with `MAXDIGITS` really big we get everything?

**Comment by ericphanson** [comment]
A mention in the docs here would be great too: https://github.com/JuliaOpt/Convex.jl/blob/master/docs/src/advanced.md#printing-and-the-tree-structure

As well as adding `Convex.MAXDIGITS` to the `@docs` block there at the end.

**Comment by riccardomurri** [comment]
I've added the docs and tests.  The test are maybe not optimal, in that they use knowledge that `show_id(x) = string(x.id_hash)` but I couldn't imagine another way of doing it.

**Comment by ericphanson** [comment]
Looks great, thanks!

**Comment by ericphanson** [comment]
0.13.2 will be released with this feature once this PR goes through in ~30 minutes https://github.com/JuliaRegistries/General/pull/10934

**Pull request merged**
