### PR TITLE
Phase recovery using relaxation similar to MaxCut 

### PR DESCRIPTION
**Pull request by Ayush-iitkgp**
Adding more applications of optimization with complex variables.
@peterwittek and @dvij I hope I have solved the problem correctly.
I also request the experts in complex-domain optimization to add more examples before we release the new version of the package.

### CODE REVIEW

**Comment by peterwittek** [comment]
Quantum steering is one area where having complex Hermitian matrices is crucial. There are a handful of examples in MATLAB in [this repo](https://github.com/paulskrzypczyk/steeringreview). This, unfortunately, needs #168 resolved first.

A much simpler is in [this Python notebook](https://github.com/peterwittek/ipython-notebooks/blob/master/Simulating_POVMs.ipynb). This can be done now. I will adapt the qubit case and send a pull request.

**Comment by peterwittek** [comment]
Done: PR #172 implements the qubit POVM simulation problem.

**Comment by madeleineudell** [comment]
@peterwittek , another very useful contribution would be to write tests and documentation for #147 - I think that's all that's required for us to have a partial trace implementation.

**Comment by Ayush-iitkgp** [comment]
Suggestion incorporated.

**Comment by madeleineudell** [comment]
Thanks, Ayush! 

Also, it would be nice to motivate why that SDP recovers the answer. I've usually seen a different setup for the phase retrieval problem. we minimize sum_{i=1}^m (|<a_i, u>|^2 - b_i)^2 . We use the fact that |<a_i, u>|^2 = (u^* a_i) (a_i^* u) = Tr[ (u^* a_i) (a_i^* u) ] = Tr[ a_i a_i^* u u^* ]. Then let U = u u^*, so that sum_{i=1}^m (|<a_i, u>|^2 - b_i)^2 = sum_{i=1}^m (Tr[ a_i a_i^* U ] - b_i)^2 is convex in U!

You should actually be able to get exact recovery of the input signal if you have more measurements than the dimension of the signal. In other words, b is an m-vector, and A is a m x n matrix, with m > n. Using m = 4n should be sufficient.

You can generate problem data by picking measurement vectors a_i to be random n-vectors, picking a true signal x to be a random n-vector, and setting each coordinate b_i = |<a_i, x>|^2 + small gaussian noise. See if you find that u is close to x!

**Comment by Ayush-iitkgp** [comment]
@madeleineudell, the original phase retrieval problem is:
>>>> find x

>>>> such that |Ax| = b

>>>> where x in {C}^p, A in C}{n×p} and b in R}^n

After going the research paper, I found that we should rather assume b and then find u using formulation above and then construct x.
I didn't get what you meant by "u is close to x". They have different dimensions. And if you meant
`atan(sum(imag(u))/sum(real(u))) == atan(sum(imag(x))/sum(real(x)))`, they don't seem to be close enough. I don't know where is the mistake that I am commiting

**Comment by Ayush-iitkgp** [comment]
ping @madeleineudell

**Comment by Ayush-iitkgp** [comment]
@madeleineudell, I am sorry for the misunderstanding. All this time we have been solving different problems. **This example is to retrieve the phase of Ax given it's magnitude**. We do not intend to find the original signal in this example. It uses the classical [MaxCut](http://www-math.mit.edu/~goemans/PAPERS/maxcut-jacm.pdf) relaxation to form a complex semidefinite programming problem.

In coming days, I would create another PR to retrieve the original signal using the methodology defined above.

**Comment by madeleineudell** [comment]
Ayush, thanks for the clarification! The writeup is wonderfully clear on this iteration, and I think I understand now. There is one thing you could do to make the solution even more nice. So far,

1. you start by generating an A and x
2. you solve for u
3. you hope that the phase of u is the phase of Ax

why don't you check?

4. compute norm( mod( phase (u) - phase (Ax), 2*pi ) )? 

(That's pseudocode; you'll want to figure out how to compute phase and which kind of norm is best.) If the problem is big enough and nicely conditioned, we should see that this number is small.

**Comment by Ayush-iitkgp** [comment]
`phase_u = atan(sum(imag(u)/sum(real(u))))
`
`phase_Ax = atan(sum(imag(A*x)/sum(real(A*x))))`

I am not sure but I am using **atan** to calculate the phase. For some random values of A and x, u and Ax point to the same direction but for some values they are not.

**Comment by madeleineudell** [comment]
Try a bigger example (more observations, ie b gets longer) and see if the
fraction of correct answers increases?

**Comment by Ayush-iitkgp** [comment]
@madeleineudell I think we should merge this PR. This example is just intended to show how to use our implemnetation. I think we can improve it once domain specific people start taking interest in our implementation. I want a new version release for Convex.jl and publicize it and this unmerged PR is one of the reasons why I am unable to proceed. I am planning to add one or two more examples and then we are ready for new Convex.jl version.

**Comment by madeleineudell** [comment]
Ayush, sounds like a fine plan.

Just a few typos first:

* the magnitude vector |Ax|, not the phase of Ax
* \mathbb{C}^{n×p} should be \mathbb{C}^{n \times p}

On Fri, Mar 17, 2017 at 12:13 PM, Ayush Pandey <notifications@github.com> wrote:
> @madeleineudell I think we should merge this PR. This example is just
> intended to show how to use our implemnetation. I think we can improve it
> once domain specific people start taking interest in our implementation. I
> want a new version release for Convex.jl and publicize it and this unmerged
> PR is one of the reasons why I am unable to proceed. I am planning to add
> one or two more examples and then we are ready for new Convex.jl version.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Madeleine Udell
Assistant Professor, Operations Research and Information Engineering
Cornell University
https://people.orie.cornell.edu/mru8/
(415) 729-4115

**Comment by Ayush-iitkgp** [comment]
Typo fixed.

**Pull request merged**
