### PR TITLE
Dot

### PR DESCRIPTION
**Pull request by madeleineudell**

### CODE REVIEW

**Comment by mlubin** [comment]
This is usually called ``vecdot`` when the arguments aren't vectors, but convex.jl is free to overload ``dot`` as well.

**Comment by madeleineudell** [comment]
I will happily bow to convention. How does this sound:

* change the name of `dot` to `vecdot`
* have `dot` point to `vecdot` for vector arguments
* `dot` for matrix arguments is an error

?

**Comment by mlubin** [comment]
Sounds good!

**Comment by madeleineudell** [comment]
Works on 4.0

**Pull request merged**
