### PR TITLE
compat fixes for 0.4

### PR DESCRIPTION
**Pull request by mlubin**
Can now run tests to completion on 0.4, but there are still numerical errors.

### CODE REVIEW

**Comment by mlubin** [comment]
I have tests passing on 0.4 with the patch from JuliaLang/julia#11236

**Comment by karanveerm** [comment]
This looks good, I was trying to fix this too locally but kept running into segfaults with Julia 0.4 :( 

Let's wait for the Julia PR to be accepted before we merge, although I think we should move away from hashing because of collisions completely (going to open a separate issue for that).

**Comment by mlubin** [comment]
Merged now, though we may want to wait a couple of days until the fix gets pushed through the binaries and we get Travis passing.

**Comment by mlubin** [comment]
All green now

**Comment by mlubin** [comment]
Could we tag a new version to get Convex passing on the package evaluator?

**Comment by jennyhong** [comment]
Will do!

**Pull request merged**
